#!/bin/bash
set -euo pipefail

cd "$(dirname $0)/.."
CLANG_FORMAT_CMD=${CLANG_FORMAT_CMD:-clang-format}
$CLANG_FORMAT_CMD --version
exec ci/run-clang-format.py \
    --clang-format-executable $CLANG_FORMAT_CMD \
    --recursive \
    core ui tests
